storage:
  # MariaDB ou SQLite
  type: "sqlite"
  mariadb:
    host: "127.0.0.1"
    port: 3306
    database: "kits"
    username: "root"
    password: "password"

pool-settings:
  maximum-pool-size: 3
  minimum-idle: 1
  maximum-lifetime: 1800000
  connection-timeout: 10000